spring:
  application:
    name: shedlock-demo-app2
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 90
      maximum-pool-size: 90